#cloud-config

write_files:
  - path: /opt/kubernetes/.kubernetes_auth
    permissions: 0600
    content: |
      {
        "User": "KUBE_USER",
        "Password": "KUBE_PASSWORD",
        "CAFile": "/etc/ssl/kubernetes/ca.crt",
        "CertFile": "/etc/ssl/kubernetes/client.crt",
        "KeyFile": "/etc/ssl/kubernetes/private/client.key"
      }
  - path: /run/rackspace-setup-environment.sh
    permissions: '0755'
    content: |
      #!/bin/bash

      ENV="/etc/environment"

      sed -i -e '/^COREOS_PUBLIC_IPV4=/d' \
          -e '/^COREOS_PRIVATE_IPV4=/d' \
          "${ENV}"

      # We spin loop until the the IP addresses are set
      function get_ip () {
          IF=$1
          IP=
          while [ 1 ]; do
              IP=$(ifconfig $IF | awk '/inet / {print $2}')
              if [ "$IP" != "" ]; then
                  break
              fi
              sleep .1
          done
          echo $IP
      }

      COREOS_PUBLIC_IPV4=$(get_ip eth0)
      COREOS_PRIVATE_IPV4=$(get_ip eth2)

      echo COREOS_PUBLIC_IPV4=$COREOS_PUBLIC_IPV4 >> $ENV
      echo COREOS_PRIVATE_IPV4=$COREOS_PRIVATE_IPV4 >> $ENV

      # systemd does not perform environment variable expansion, thus no drop-ins.
      # http://www.freedesktop.org/software/systemd/man/systemd.exec.html#Environment=
      echo ETCD_ADVERTISE_CLIENT_URLS=http://$COREOS_PRIVATE_IPV4:2379 >> $ENV
      echo ETCD_INITIAL_ADVERTISE_PEER_URLS=http://$COREOS_PRIVATE_IPV4:2380 >> $ENV
      echo ETCD_LISTEN_CLIENT_URLS=http://localhost:2379,http://$COREOS_PRIVATE_IPV4:2379 >> $ENV
      echo ETCD_LISTEN_PEER_URLS=http://$COREOS_PRIVATE_IPV4:2380 >> $ENV
      #
      echo FLEET_PUBLIC_IP=$COREOS_PRIVATE_IPV4 >> $ENV
  - path: /etc/profile.d/basepath.sh
    permissions: 0644
    owner: core
    content: |
      export PATH="/opt/bin:$PATH"
  - path: /etc/profile.d/etcdctl.sh
    permissions: 0644
    owner: core
    content: |
      export ETCDCTL_PEERS="http://127.0.0.1:2379"
  - path: /etc/profile.d/fleetctl.sh
    permissions: 0644
    owner: core
    content: |
      export FLEETCTL_ENDPOINT=http://127.0.0.1:2379
  # - path: /opt/kubernetes/bin/kube-apiserver-finder.sh
  #   permissions: 0755
  #   content: |
  #     #!/bin/sh
  #     m=$(echo $(etcdctl ls --recursive /corekube/apiservers | cut -d/ -f4 | sort) | tr ' ' ,)
  #     mkdir -p /run/kubelet
  #     echo "APISERVER_IPS=$m" > /run/kubelet/apiservers.env
  #     echo "FIRST_APISERVER_URL=https://${m%%\,*}:6443" >> /run/kubelet/apiservers.env
coreos:
  etcd:
    discovery: https://discovery.etcd.io/DISCOVERY_ID
    ca_file: /etc/ssl/etcd/certs/ca.crt
    cert_file: /etc/ssl/etcd/certs/server.crt
    key_file: /etc/ssl/etcd/private/server.key
    peer_ca_file: /etc/ssl/etcd/certs/ca.crt
    peer_cert_file: /etc/ssl/etcd/certs/peer.crt
    peer_key_file: /etc/ssl/etcd/private/peer.key
  flannel:
    interface: eth2
    ip_masq: yes
  fleet:
    metadata: kubernetes_role=minion
    etcd_servers: http://127.0.0.1:2379
  update:
    reboot-strategy: etcd-lock
  units:
    - name: rackspace-setup-environment.service
      runtime: true
      command: start
      content: |
        [Unit]
        Description=Setup environment with private (and public) IP addresses
        Wants=coreos-setup-environment.service
        After=coreos-setup-environment.service

        [Service]
        Type=oneshot
        RemainAfterExit=yes
        ExecStart=/run/rackspace-setup-environment.sh
    - name: etcd.service
      command: start
      content: |
        [Unit]
        Description=etcd 2.0
        After=docker.service
        ConditionPathIsDirectory=/etc/ssl/etcd/private

        [Service]
        EnvironmentFile=/etc/environment
        Environment=ETCD_DATA_DIR=/var/lib/etcd
        Environment=ETCD_NAME=%m
        ExecStartPre=-/usr/bin/docker kill etcd
        ExecStartPre=-/usr/bin/docker rm etcd
        ExecStartPre=/usr/bin/docker pull quay.io/coreos/etcd:v2.0.5
        ExecStart=/usr/bin/docker run \
          --net host \
          --name etcd \
          -v /opt/etcd:/opt/etcd \
          -v /usr/share/ca-certificates:/etc/ssl/certs \
          -v /etc/ssl/etcd:/etc/ssl/etcd \
          quay.io/coreos/etcd:v2.0.5 \
          -data-dir ${ETCD_DATA} \
          -name ${ETCD_NAME} \
          -discovery ${ETCD_DISCOVERY} \
          -ca-file ${ETCD_CA_FILE} \
          -cert-file ${ETCD_CERT_FILE} \
          -key-file ${ETCD_KEY_FILE} \
          -peer-ca-file ${ETCD_PEER_CA_FILE} \
          -peer-cert-file ${ETCD_PEER_CERT_FILE} \
          -peer-key-file ${ETCD_PEER_KEY_FILE} \
          -advertise-client-urls ${ETCD_ADVERTISE_CLIENT_URLS} \
          -initial-advertise-peer-urls ${ETCD_INITIAL_ADVERTISE_PEER_URLS} \
          -listen-client-urls ${ETCD_LISTEN_CLIENT_URLS} \
          -listen-peer-urls ${ETCD_LISTEN_PEER_URLS}
        ExecStop=/usr/bin/docker kill etcd
        SyslogIdentifier=etcd
        Restart=always
        RestartSec=10s
        LimitNOFILE=40000
    - name: fleet.service
      command: start
      drop-ins:
        - name: 50-network-config.conf
          content: |
            [Unit]
            Requires=etcd.service
            After=etcd.service

            [Service]
            EnvironmentFile=/etc/environment
    - name: flanneld.service
      command: start
    - name: update-etcdctl.service
      command: start
      content: |
          [Unit]
          Descritpion=updates etcdctl to v2.0

          [Service]
          Type=oneshot
          RemainAfterExit=yes
          ExecStart=/usr/bin/curl -L https://github.com/coreos/etcd/releases/download/v2.0.5/etcd-v2.0.5-linux-amd64.tar.gz -o /tmp/etcd-v2.0.5-linux-amd64.tar.gz
          ExecStart=/usr/bin/tar zxf /tmp/etcd-v2.0.5-linux-amd64.tar.gz -C /tmp
          ExecStart=/usr/bin/mkdir -p /opt/bin
          ExecStart=/usr/bin/cp /tmp/etcd-v2.0.5-linux-amd64/etcdctl /opt/bin
    # - name: download-kubernetes.service
    #   command: start
    #   content: |
    #     [Unit]
    #     Description=Downloads Kubernetes Release
    #     After=network-online.target
    #     Requires=network-online.target
    #
    #     [Service]
    #     Type=oneshot
    #     RemainAfterExit=yes
    #     ExecStartPre=/usr/bin/wget CLOUD_FILES_URL -O /tmp/kubernetes.tar.gz
    #     ExecStartPre=/usr/bin/mkdir -p /opt/kubernetes
    #     ExecStart=/usr/bin/tar xzf /tmp/kubernetes.tar.gz --strip 1 -C /opt/kubernetes/
    # - name: kubelet.service
    #   command: start
    #   content: |
    #     [Unit]
    #     Description=Kubernetes Kubelet
    #     Documentation=https://github.com/GoogleCloudPlatform/kubernetes
    #     After=download-kubernetes.service
    #     Requires=download-kubernetes.service
    #     ConditionPathExists=/etc/ssl/kubernetes/
    #     ConditionPathExists=/run/kubelet/apiservers.env
    #
    #     [Service]
    #     EnvironmentFile=/etc/environment
    #     EnvironmentFile=/run/kubelet/apiservers.env
    #     ExecStartPre=/usr/bin/ln -sf /opt/kubernetes/bin/kubelet /opt/kubernetes/bin/kubelet
    #     ExecStart=/opt/kubernetes/bin/kubelet \
    #       --address=${COREOS_PRIVATE_IPV4} \
    #       --hostname_override=${COREOS_PRIVATE_IPV4} \
    #       --api_servers=${FIRST_APISERVER_URL} \
    #       --logtostderr=true \
    #       --config=/opt/kubernetes/kubernetes-manifests \
    #       --cluster_dns=DNS_SERVER_IP \
    #       --cluster_domain=DNS_DOMAIN \
    #       --auth_path=/opt/kubernetes/.kubernetes_auth
    #     Restart=always
    #     RestartSec=2
    # - name: kube-proxy.service
    #   command: start
    #   content: |
    #     [Unit]
    #     Description=Kubernetes Proxy
    #     Documentation=https://github.com/GoogleCloudPlatform/kubernetes
    #     After=download-kubernetes.service
    #     Requires=download-kubernetes.service
    #     ConditionPathExists=/run/kubelet/apiservers.env
    #
    #     [Service]
    #     EnvironmentFile=/etc/environment
    #     EnvironmentFile=/run/kubelet/apiservers.env
    #     ExecStartPre=/usr/bin/ln -sf /opt/kubernetes/bin/kube-proxy /opt/kubernetes/bin/kube-proxy
    #     ExecStart=/opt/kubernetes/bin/kube-proxy --bind_address=${COREOS_PRIVATE_IPV4} --master=${FIRST_APISERVER_URL} --logtostderr=true
    #     Restart=always
    #     RestartSec=2
    # - name: kube-apiserver-finder.service
    #   command: start
    #   content: |
    #     [Unit]
    #     Description=Kubernetes Apiserver Finder
    #     After=download-kubernetes.service
    #     Requires=download-kubernetes.service
    #     After=etcd.service
    #     Requires=etcd.service
    #
    #     [Service]
    #     ExecStartPre=/opt/kubernetes/bin/kube-apiserver-finder.sh
    #     ExecStart=/usr/bin/etcdctl exec-watch --recursive /corekube/apiservers -- /opt/kubernetes/bin/kube-apiserver-finder.sh
    #     Restart=always
    #     RestartSec=30
